// examples/router-react/src/main.tsx
import { RegistryProvider } from "@effect/atom-react"
import { StrictMode } from "react"
import { createRoot } from "react-dom/client"
import { App } from "./App.tsx"
import "./styles.css"

const root = document.querySelector("#root")

if (root === null) {
  throw new Error("Missing #root element")
}

createRoot(root).render(
  <StrictMode>
    <RegistryProvider>
      <App />
    </RegistryProvider>
  </StrictMode>
)

// packages/router/examples/solid/src/main.tsx
import { RegistryProvider } from "@effect/atom-solid"
import { render } from "solid-js/web"
import { App } from "./App.tsx"
import "./styles.css"

const root = document.querySelector("#root")

if (root === null) {
  throw new Error("Missing #root element")
}

render(() => (
  <RegistryProvider>
    <App />
  </RegistryProvider>
), root)
